const API_KEY = "AIzaSyC2Rvn6LU0c3lFxLe-nklVFOyHgIe9jH8Q";

export const YOUTUBE_VIDEOS_API =
  process.env.REACT_APP_YOUTUBE_VIDEOS_API + API_KEY;

export const YOUTUBE_SEARCH_API = process.env.REACT_APP_YOUTUBE_SEARCH_API;

export const YOUTUBE_SEARCH_SUGGESTION_API =
  process.env.REACT_APP_YOUTUBE_SEARCH_SUGGESTION_API + API_KEY;
